# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provador',
            options={'verbose_name': 'Provadore'},
        ),
    ]
