# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Amostras',
                'verbose_name': 'Amostra',
            },
        ),
        migrations.CreateModel(
            name='AnaliseSensorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_Inicio', models.DateField()),
                ('time_Inicio', models.TimeField()),
                ('time_Final', models.TimeField()),
                ('data_Final', models.DateField()),
                ('possui_amostras', models.BooleanField()),
                ('ativado', models.BooleanField()),
                ('quantidade_amostras', models.IntegerField()),
                ('quantidade_pessoas', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('tipo', models.CharField(choices=[('PSN', 'Pergunta sim/não'), ('PHD', 'Pergunta hedônica'), ('PDT', 'Pergunta dissertativa'), ('PIC', 'Pergunta de inteção de compra')], max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Perguntas',
                'verbose_name': 'Pergunta',
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.AnaliseSensorial')),
                ('provador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.Provador')),
            ],
            options={
                'verbose_name_plural': 'Testes sensoriais',
                'verbose_name': 'Teste sensorial',
            },
        ),
        migrations.CreateModel(
            name='PerguntaDissertativa',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Fabricante.Pergunta')),
                ('descricao', models.TextField()),
            ],
            bases=('Fabricante.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaHedonica',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Fabricante.Pergunta')),
                ('hedonica', models.IntegerField(choices=[(1, 'Desgostei extremamente (detestei)'), (2, 'Desgostei muito'), (3, 'Desgostei moderadamente'), (4, 'Desgostei ligeiramente'), (5, 'Nem gostei / Nem desgostei'), (6, 'Gostei ligeiramente'), (7, 'Gostei moderadamente'), (8, 'Gostei muito'), (9, 'Gostei muitíssimo (adorei)')], null=True)),
            ],
            bases=('Fabricante.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaIntencaoCompra',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Fabricante.Pergunta')),
                ('compra', models.IntegerField(choices=[(1, 'Certamente não compraria o produto'), (2, 'Possivelmente não compraria o produto'), (3, 'Talvez comprasse / Talvez não comprasse'), (4, 'Possivelmente compraria o produto'), (5, 'Certamente compraria o produto')], null=True)),
            ],
            bases=('Fabricante.pergunta',),
        ),
        migrations.CreateModel(
            name='PerguntaSimNao',
            fields=[
                ('pergunta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Fabricante.Pergunta')),
                ('nao', models.BooleanField(default=False, verbose_name='Não')),
                ('sim', models.BooleanField(default=False, verbose_name='Sim')),
            ],
            bases=('Fabricante.pergunta',),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.AnaliseSensorial'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.AnaliseSensorial'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='teste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.Teste'),
        ),
    ]
