# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Amostra',
                'verbose_name_plural': 'Amostras',
            },
        ),
        migrations.CreateModel(
            name='AnaliseSensorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_Inicio', models.DateTimeField()),
                ('data_Final', models.DateTimeField()),
                ('possui_amostras', models.BooleanField()),
                ('ativado', models.BooleanField()),
                ('quantidade_amostras', models.IntegerField()),
                ('quantidade_pessoas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Análise',
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.AnaliseSensorial')),
            ],
            options={
                'verbose_name': 'Teste sensorial',
                'verbose_name_plural': 'Testes sensoriais',
            },
        ),
    ]
