# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='tipo',
        ),
    ]
