# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webpage', '0001_initial'),
        ('Fabricante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='provador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.Provador'),
        ),
        migrations.AddField(
            model_name='analisesensorial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amostra',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.AnaliseSensorial'),
        ),
        migrations.AddField(
            model_name='amostra',
            name='teste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.Teste'),
        ),
    ]
