# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Numeros_Aleatorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_amostras', models.CharField(choices=[('2', '2'), ('3', '3')], max_length=1)),
                ('quantidade_pessoas', models.CharField(choices=[('60', '60'), ('30', '30'), ('90', '90'), ('120', '120'), ('150', '150'), ('180', '180'), ('210', '210'), ('240', '240'), ('270', '270'), ('300', '300')], max_length=5)),
                ('ativado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Numero_Aleatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('utilizado', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='analise_dados_pessoais',
            options={'verbose_name': 'Análise'},
        ),
        migrations.AddField(
            model_name='numero_aleatorio',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.Analise_Dados_Pessoais'),
        ),
        migrations.AddField(
            model_name='dados_numeros_aleatorios',
            name='analise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.Analise_Dados_Pessoais'),
        ),
    ]
