# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='amostra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fabricante.Amostra'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='teste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fabricante.Teste'),
        ),
    ]
