# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0002_auto_20160801_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amostra',
            options={'verbose_name': 'Amostra', 'verbose_name_plural': 'Amostras'},
        ),
        migrations.AlterField(
            model_name='teste',
            name='provador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.Provador'),
        ),
    ]
