# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0002_remove_pergunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('PSN', 'Pergunta sim/não'), ('PHD', 'Pergunta hedônica'), ('PDT', 'Pergunta dissertativa'), ('PIC', 'Pergunta de inteção de compra')], default=datetime.datetime(2016, 9, 10, 21, 36, 57, 249671, tzinfo=utc), max_length=4),
            preserve_default=False,
        ),
    ]
