# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0002_auto_20160823_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'PerguntaSimNao'), (2, 'PerguntaHedonica'), (3, 'PerguntaDissertativa')], default=None),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.AnaliseSensorial'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='teste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricante.Teste'),
        ),
        migrations.AlterField(
            model_name='analisesensorial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perguntahedonica',
            name='hedonica',
            field=models.IntegerField(choices=[(1, 'Desgostei Muitissimo'), (2, 'Desgostei Moderadamente'), (3, 'Gostei'), (4, 'Gostei Moderadamente'), (5, 'Gostei Muitissimo')], default=5, null=True),
        ),
    ]
