# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0002_auto_20160731_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_numeros_aleatorios',
            name='quantidade_amostras',
            field=models.CharField(choices=[('2', '2'), ('3', '3')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='dados_numeros_aleatorios',
            name='quantidade_pessoas',
            field=models.CharField(choices=[('60', '60'), ('30', '30'), ('90', '90'), ('120', '120'), ('150', '150'), ('180', '180'), ('210', '210'), ('240', '240'), ('270', '270'), ('300', '300')], default='180', max_length=5),
        ),
    ]
