# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0003_auto_20160830_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='perguntasimnao',
            name='nao',
        ),
        migrations.RemoveField(
            model_name='perguntasimnao',
            name='sim',
        ),
        migrations.AddField(
            model_name='perguntasimnao',
            name='boolean',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=None),
        ),
    ]
