# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0003_pergunta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntasimnao',
            name='nao',
        ),
        migrations.RemoveField(
            model_name='perguntasimnao',
            name='sim',
        ),
        migrations.AddField(
            model_name='perguntasimnao',
            name='resposta',
            field=models.BooleanField(default=False),
        ),
    ]
