# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricante', '0004_auto_20160830_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntasimnao',
            name='boolean',
        ),
        migrations.AddField(
            model_name='perguntasimnao',
            name='nao',
            field=models.BooleanField(default=False, verbose_name='Não'),
        ),
        migrations.AddField(
            model_name='perguntasimnao',
            name='sim',
            field=models.BooleanField(default=False, verbose_name='Sim'),
        ),
    ]
